name: Import APIs to APIM

on:
  push:
    branches:
      - main

jobs:
  import-apis:
    runs-on: ubuntu-latest
    name: Import APIs

    steps:
      - uses: actions/checkout@v2

      - name: Install yq
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Import APIs
        run: |
          for file in ./openapi/*.yaml; do
            baseName=$(basename "$file" .yaml)
            serviceUrl=$(yq e '.servers[0].url' $file)
            versionId=$(yq e '.info.version' $file)
            displayName="$baseName-$versionId"
            az apim api import --resource-group ${{ secrets.RESOURCE_GROUP }} --service-name ${{ secrets.APIM_INSTANCE }} --path $baseName --api-type http --api-id $baseName --display-name $displayName --service-url $serviceUrl --protocols https --specification-format OpenApi --specification-path $file
            accessToken=$(az account get-access-token --query accessToken -o tsv)
            subscriptionId=$(az account show --query id -o tsv)
            apiId=$(az apim api list --resource-group ${{ secrets.RESOURCE_GROUP }} --service-name ${{ secrets.APIM_INSTANCE }} --query "[?name=='$baseName'].apiId" -o tsv)
            curl -X PATCH -H "Authorization: Bearer $accessToken" -H "Content-Type: application/json" -d "{ \"properties\": { \"apiVersion\": \"$versionId\" } }" https://management.azure.com/subscriptions/$subscriptionId/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.ApiManagement/service/${{ secrets.APIM_INSTANCE }}/apis/$apiId?api-version=2019-01-01
          done

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script
        run: python ./apiazure.py
        env:
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          apimServiceName: ${{ secrets.APIM_INSTANCE }}
          tenantId: ${{ secrets.TENANT_ID }}
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Run api-create-update.py
        run: python api-create-update.py ${{ github.sha }}
        env:
            clientId: ${{ secrets.CLIENT_ID }}
            clientSecret: ${{ secrets.CLIENT_SECRET }}
            resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
            apimServiceName: ${{ secrets.APIM_INSTANCE }}
            tenantId: ${{ secrets.TENANT_ID }}
            subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
